apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: devops-tools
data:
  key: QVFCc2pDMWdOblJNRVJBQWR3aUNVc0lJdzlML1pXMnlscU5udFE9PQ==
#  key: AQBsjC1gNnRMERAAdwiCUsIIw9L/ZW2ylqNntQ==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifacts
  namespace: devops-tools
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  rbd:
    monitors:
      - 192.168.1.4:6789
    pool: cluster-storage
    image: myvol
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifacts-claim
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops-tools
  annotations:
    metallb.universe.tf/address-pool: default
    external-dns.alpha.kubernetes.io/hostname: artifacts.sunshower.cloud
spec:
  selector:
    app: nexus-server
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8081
    - port: 5000
      name: docker
      protocol: TCP
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
#          persistentVolumeClaim:
#            claimName: artifacts-claim
          emptyDir: {}