apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    name: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.7.6
          args:
            - --registry=txt
            - --txt-prefix=external-dns-
            - --txt-owner-id=k8s
            - --provider=rfc2136
            - --rfc2136-host=192.168.1.2
            - --rfc2136-port=53
            - --rfc2136-zone=sunshower.cloud
            - --rfc2136-tsig-axfr
            - --rfc2136-insecure
            - --source=ingress
            - --source=service
            - --domain-filter=sunshower.cloud
