apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifacts
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  rbd:
    monitors:
      - athena.sunshower.io:6789
    pool: virtual-machines
    image: myvol
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifacts-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi