---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: build
  namespace: devops-tools
spec:
  storageClassName: csi-rbd
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 192.168.1.4:6789
      - 192.168.1.3:6789
    pool: kubernetes
    image: build
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: build-claim
  namespace: devops-tools
spec:
  storageClassName: csi-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
